YEARS = {
    2022: "două mii douăzeci și doi",
    2023: "două mii douăzeci și trei",
    2024: "două mii douăzeci și patru",
    2025: "două mii douăzeci și cinci",
    2026: "două mii douăzeci și șase",
    2027: "două mii douăzeci și șapte",
    2028: "două mii douăzeci și opt",
    2029: "două mii douăzeci și nouă",
    2030: "două mii douăzeci și zece",
}

MONTHS = {
    1: "ianuarie",
    2: "februarie",
    3: "martie",
    4: "aprilie",
    5: "mai",
    6: "iunie",
    7: "iulie",
    8: "august",
    9: "septembrie",
    10: "octombrie",
    11: "noiembrie",
    12: "decembrie",
}

NUMBERS = {
    1: "unu",
    2: "doi",
    3: "trei",
    4: "patru",
    5: "cinci",
    6: "șase",
    7: "șapte",
    8: "opt",
    9: "nouă",
    10: "zece",
    11: "unsprezece",
    12: "doisprezece",
    13: "treisprezece",
    14: "paisprezece",
    15: "cincisprezece",
    16: "șaisprezece",
    17: "șaptesprezece",
    18: "optsprezece",
    19: "nouăsprezece",
    20: "douăzeci",
    21: "douăzeci și unu",
    22: "douăzeci și doi",
    23: "douăzeci și trei",
    24: "douăzeci și patru",
    25: "douăzeci și cinci",
    26: "douăzeci și șase",
    27: "douăzeci și șapte",
    28: "douăzeci și opt",
    29: "douăzeci și nouă",
    30: "treizeci",
    31: "treizeci și unu",
    40: "patruzeci",
    50: "cincizeci",
    60: "șaizeci",
    70: "șaptezeci",
    80: "optzeci",
    90: "nouăzeci",
    100: "una sută",
    200: "două sute",
    300: "trei sute",
    400: "patru sute",
    500: "cinci sute",
    600: "șase sute",
    700: "șapte sute",
    800: "opt sute",
    900: "nouă sute",
    1000: "una mie",
    2000: "două mii",
    3000: "trei mii",
    4000: "patru mii",
    5000: "cinci mii",
    6000: "șase mii",
    7000: "șapte mii",
    8000: "opt mii",
    9000: "nouă mii",
}
