# Generated by Django 4.0.1 on 2022-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_client_created_client_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ImageField(upload_to='')),
                ('back', models.ImageField(upload_to='')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
