# Generated by Django 4.0.1 on 2022-01-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_client_back_client_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='generated_doc',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
