# Generated by Django 4.0.4 on 2022-04-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_client_cost_client_registration_number_client_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='receipt',
            field=models.FileField(default='templates/template-chitanta.docx', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='receipt_number',
            field=models.PositiveIntegerField(default=12344556),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='receipt_series',
            field=models.CharField(default='DAA', max_length=100),
        ),
    ]
